### ISSUE TITLE
Bibtex entries should point to html not to pdf

### ISSUE THREAD

**Issue by JeffFessler** [mlresearch/v158#4]
The bibtex entries point to the pdf with a url like this:
https://proceedings.mlr.press/v158/truong21a/truong21a.pdf
but it would be preferable to point to the html
https://proceedings.mlr.press/v158/truong21a.html
so that people can see the abstract and the metadata etc.
It's then only one more click to get the pdf...

**Comment by lawrennd** [comment]
Nice point Jeff, I'm ashamed because I'm often railing against the use of pdf links! Would adding a field "url" be the right fix in your opinion?

**Comment by JeffFessler** [comment]
Thanks for the quick reply!  Having an additional url field does seem best, because then both the pdf link lovers and the pdf link lamenters can be happy :)
I hope it is something that is easy to automate.  Oh wait, it looks like you already did it - hooray!
(Either that or it was there all along and my own bibtex parsing script missed it, in which case I am the one who should be embarassed...)

I checked a random paper in NeurIPS 2021 and the bibtex there also had the html url, so (by a sample size of 2) it looks like you have fixed this globally for PMLR.  Thanks!
BTW, the proceedings specs seem to be silent on the topic of what url(s) to put in the bibtex file: https://proceedings.mlr.press/spec.html
I'm closing the issue since it looks great to me.
